### ISSUE TITLE
Cannot download pdf if openning in a new tab

### ISSUE THREAD

**Issue by sukanzubair** [tossnet/Blazor-PDF#2]
Hi,

If i view the pdf in the iframe i am able to click the download button and the save dialog pops up.
If i open the PDF in a new tab and try to select the download icon it does not do anything. 
Do you perhaps know why this is the case and if there is a way i can resolve this?

Thanks
Zubair

**Comment by tossnet** [comment]
I can see that. I currently don't know why :/

**Comment by tossnet** [comment]
I found a solution. The source code is up to date.

**Comment by sukanzubair** [comment]
Great, i will have a look and let you know if it works on my end. Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [tossnet/Blazor-PDF] Cannot download pdf if openning in a new tab (#2)From: Christophe Peugnet To: tossnet/Blazor-PDF CC: sukanzubair ,Author 
I found a solution. The source code is up to date.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/tossnet/Blazor-PDF/issues/2#issuecomment-719689708",
"url": "https://github.com/tossnet/Blazor-PDF/issues/2#issuecomment-719689708",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
